version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_telemetry
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_telemetry
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <YOUR_HOST_MACHINE_IP>  # Replace with your host machine's IP address
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:
      - postgres
      
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'Datapipeline_DB'
      POSTGRES_USER: 'Datapipeline_DB_user'
      POSTGRES_PASSWORD: 'Datapipeline_DB_pwd'

networks:
  default:
    external:
      name: 'myNetwork_Datapipeline'
